### ISSUE TITLE
Create AudioDSP V2 Road Map

### ISSUE THREAD

**Issue by AchimTuran** [AchimTuran/xbmc#21]
## Detailed Description

Within this issue a road map for developing AudioDSP V2.0 will be created [here](https://github.com/AchimTuran/xbmc/projects/1).

### Context

I really like to share the development process with everyone who is interested in Audio Digital Signal Processing (AudioDSP) for [Kodi](https://kodi.tv/). In the [past](https://forum.kodi.tv/showthread.php?tid=252871) I already worked on this feature and took a break to learn new skills and to create a better workflow for C/C++ signal processing applications like AudioDSP.

### Implementation Proposal

The AudioDSP extension point will be integrated into [ActiveAE](https://kodi.wiki/view/AudioEngine), Kodi's audio engine. The integration will be implemented as an audio buffer, which makes it possible to enable or disable the AudioDSP extension point on the fly during watching a video or listening to music. This can be done by the On Screen Display (OSD) menu or in the audio system settings from Kodi. So you will be always able to listen to the difference between the audio signals.

*Note: Team Kodi is considering this item, but we are not making any promises if and when it will be included.*

**Comment by zag2me** [comment]
Just for info, the Kodi thread is Read only for normal users. Just letting you know why there are no replies there... :)

**Comment by AchimTuran** [comment]
@zag2me 
Thanks a lot! I totally forgot that we made the sub forum read only... :-)

**Comment by AchimTuran** [comment]
@zag2me 
Can you please test if you now have write rights? The issue should be fixed now.

@ronie
For fixing the issue!

**Comment by zag2me** [comment]
Thx works.

**Comment by AchimTuran** [comment]
Roadmap seems to be ok. Therefore this issue will be marked as done.
